import io
import warnings
from pathlib import Path

import numpy as np
import torch
from kokoro import KPipeline
from pydub import AudioSegment

def kokoro_local_tts_to_mp3(
    text: str,
    output_path: str,
    model_id: str = "hexgrad/Kokoro-82M",
    lang_code: str = "a",
    voice: str = "af_heart",
    speed: float = 1.0,
    split_pattern: str = r"\n+",
) -> None:
    """
    Synthesize `text` with Kokoro-82M locally and save as an MP3.

    - Suppresses the PyTorch RNN dropout warning.
    - Explicitly passes repo_id to avoid the defaulting warning.
    - Converts float32 [-1,1] audio to signed 16-bit PCM before packaging.
    """
    # 1️⃣ Silence that RNN dropout warning
    warnings.filterwarnings(
        "ignore",
        category=UserWarning,
        message=r".*dropout option adds dropout after all but last recurrent layer.*"
    )

    # 2️⃣ Initialize the pipeline with explicit repo_id
    pipeline = KPipeline(
        repo_id=model_id,
        lang_code=lang_code,
    )

    # 3️⃣ Generate raw float32 audio tensors
    generator = pipeline(
        text,
        voice=voice,
        speed=speed,
        split_pattern=split_pattern,
    )

    # 4️⃣ Convert each chunk to 16-bit PCM and load as a raw AudioSegment
    segments = []
    for _, _, audio_tensor in generator:
        # Tensor → NumPy float32 array in [-1,1]
        audio_np = audio_tensor.cpu().detach().numpy()

        # Float32 → int16 PCM
        audio_int16 = (audio_np * 32767).clip(-32768, 32767).astype(np.int16)

        # Load raw PCM data
        segment = AudioSegment.from_raw(
            io.BytesIO(audio_int16.tobytes()),
            sample_width=2,    # 2 bytes per sample for int16
            frame_rate=24000,  # Kokoro outputs at 24 kHz
            channels=1,
        )
        segments.append(segment)

    if not segments:
        raise RuntimeError("No audio generated by Kokoro pipeline.")

    # 5️⃣ Concatenate all segments and export as MP3
    combined = segments[0]
    for seg in segments[1:]:
        combined += seg

    out_file = Path(output_path)
    combined.export(out_file, format="mp3")

    print(f"Synthesized speech saved to {out_file.resolve()}")



if __name__ == "__main__":
    sentence = "Quelle rue cherchez-vous ?"
    kokoro_local_tts_to_mp3(
        text=sentence,
        output_path="hello_local.mp3",
        lang_code="f",
        voice="ff_siwis",
        speed=1.0,
    )
